ALTER TABLE tracking ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE tracking ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE tracking ADD COLUMN IF NOT EXISTS confirmed_by TEXT;
ALTER TABLE tracking ADD COLUMN IF NOT EXISTS no_resi TEXT;
ALTER TABLE tracking ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
